### PR TITLE
Remove  unnecessary lines

### PR DESCRIPTION
**Pull request by msabramo**

### CODE REVIEW

**Comment by rocky** [comment]
Please don't remove the pass lines. It is a misfeature of Python that it doesn't have a terminator to a block. (People often say it is the indentation that is the misfeature, but I don't care about that.) 

The pass adds redundancy so that when the code is refactored one knows where the end is. In the olden days Emacs would also grok that "pass" was the end of a block in the same way that "return" is the end of a block. 

Yes, this may be an idiosyncracy of mine. But it's also my project. Just chalk it up to some weirdness like allowing "make test".

**Comment by msabramo** [comment]
Ok, no problem. It's your project. I'll respect that.

**Comment by rocky** [comment]
Thanks. I appreciate it.

**Comment by rocky** [comment]
BTW, when I looked at code written by Donald Knuth, Larry Wall, David Korn, or Ken Thompson,  I recall noting there style was very different from the style of  Pascal, Perl, POSIX Shell or C that style folks obscess over for each of those languages. But in each case that I found, getting past that superficial aspect their code is pretty neat. And furthermore I also could understand a logic behind why they wrote in the particular way that they did. 

No way am I at the level of any of these folks. I'm just saying that there's a difference between style and substance. To me merging the two branches of horizontal and vertial code (which you'll find in the Ruby code) far outweight the use of a name == main, or an extra pass (which pypy or a peephole optimizser should remove). 

So again thanks. BTW, I first leared of name = main from Dive into Python. Mark Pilgram had to remove that though when he revised for Python3.  A pity.

**Comment by msabramo** [comment]
Does it not work in Python 3?

**Comment by rocky** [comment]
It's not about Python3 per se, but a change in the view of the Python committee that has made it harder to use main code in modules. This has been in conjunction with the change to go from easy_install to pip and various loader changes over time. 

The Python3 aspect was just the _reason_ I think that Mark felt compelled to revise his book. 

The thing that has kind of always pissed me off about Python in general is many/most other language swill do something in one way, and user ask for the feature over and over again and then Python goes off and does it in another way for not a suitably good reason. 

Take backtick for example. This was originally in POSIX shell. Perl adopted it, then so did Ruby. Python doesn't and only very very late in the game was the subprocess module added. 

Variable interpolation, same thing. It was in POSIX shell, then Perl, then Ruby (but probably other languages as well). Python originally no. Then when people clamor for it enough, it gets added in a slightly different way that isn't sufficiently better to justify its being different.

**Pull request closed without merging**
