### PR TITLE
Make sure py.test can find and run tests

### PR DESCRIPTION
**Pull request by msabramo**
Before when running py.test or tox, it wasn't running any tests.

I ended up getting rid of the `test` directory and putting the tests in a single file called `test_columnize.py`.

```
❯ make test
tox
GLOB sdist-make: /Users/marca/dev/git-repos/pycolumnize/setup.py
py26 inst-nodeps: /Users/marca/dev/git-repos/pycolumnize/.tox/dist/columnize-0.3.6-01.zip
py26 runtests: PYTHONHASHSEED='1074701345'
py26 runtests: commands[0] | py.test
============================================================================= test session starts ==============================================================================
platform darwin -- Python 2.6.8 -- py-1.4.26 -- pytest-2.6.4
collected 2 items

test_columnize.py ..

=========================================================================== 2 passed in 0.05 seconds ===========================================================================
py27 inst-nodeps: /Users/marca/dev/git-repos/pycolumnize/.tox/dist/columnize-0.3.6-01.zip
py27 runtests: PYTHONHASHSEED='1074701345'
py27 runtests: commands[0] | py.test
============================================================================= test session starts ==============================================================================
platform darwin -- Python 2.7.6 -- py-1.4.26 -- pytest-2.6.4
collected 2 items

test_columnize.py ..

=========================================================================== 2 passed in 0.05 seconds ===========================================================================
pypy inst-nodeps: /Users/marca/dev/git-repos/pycolumnize/.tox/dist/columnize-0.3.6-01.zip
pypy runtests: PYTHONHASHSEED='1074701345'
pypy runtests: commands[0] | py.test
============================================================================= test session starts ==============================================================================
platform darwin -- Python 2.7.8[pypy-2.4.0-final] -- py-1.4.26 -- pytest-2.6.4
collected 2 items

test_columnize.py ..

=========================================================================== 2 passed in 0.14 seconds ===========================================================================
___________________________________________________________________________________ summary ____________________________________________________________________________________
  py26: commands succeeded
  py27: commands succeeded
  pypy: commands succeeded
  congratulations :)
```

### CODE REVIEW

**Comment by rocky** [comment]
Travis fails, but I'm sure you are aware of that and are working on it. Please, when possible, it would help me if you got all this stuff done before the pull request. Thanks.

**Comment by msabramo** [comment]
Yep, will try. Trouble here is it's failing on Travis but not locally for me so it's a bit trial and error.

**Comment by msabramo** [comment]
Ah, there we go. Travis passing now. Sorry for the disruption.

**Comment by rocky** [comment]
Here's a suggestion for the future.  Adjust your project to turn on travis.
https://github.com/msabramo/pycolumnize/settings/hooks
Then when you commit, you'll get notified of the failure.

**Comment by rocky** [comment]
Thanks.

**Comment by msabramo** [comment]
Ah yeah. Usually I do turn on Travis for my forks. I didn't in this case, but I should have. I'll do that now.

**Pull request merged**
